# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Eth' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Eth
  pod 'Geth', '1.7.3' # Change the version to the latest release
	
  target 'Eth-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EthTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Eth-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Eth-tvOS

end
